name: agriplant
description: Agriculture plant app
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_iconly: ^1.0.2
  google_fonts: ^6.2.1
  badges: ^3.1.1
  timelines: ^0.1.0
  easy_stepper: ^0.8.5+1
  provider: ^6.1.2
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_ui_firestore: ^1.7.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/services/
    - shorebird.yaml
