name: agriplant
description: Agriculture plant app
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_iconly: ^1.0.2
  google_fonts: ^6.2.1
  badges: ^3.1.1
  timelines: ^0.1.0
  easy_stepper: ^0.8.5+1
  provider: ^6.1.2
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_ui_firestore: ^1.7.1
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  firebase_auth: ^5.5.1
  shared_preferences: ^2.5.2
  firebase_storage: ^12.4.4
  pinput: ^5.0.1
  country_picker: ^2.0.27
  get: ^4.6.1
  geolocator: ^9.0.1
  geocoding: ^2.0.4
  sleek_circular_slider: ^2.0.1

  fl_chart: ^0.70.2
  # intl: ^0.20.2
  # https:
  flutter_paypal_payment: ^1.0.8
  google_maps_flutter: ^2.12.0
  # http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/raster/
    - assets/services/
    - assets/icons/
    - assets/weather/
    - assets/crop/
    - assets/crop/images/
    - assets/crop/crop_image/
    - shorebird.yaml
